config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 500 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, 
    uniqueness: { case_sensitive: false }, 
    length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
    uniqueness: { case_sensitive: false }, 
    length: { maximum: 105 },
    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user, except: %i[ show index]
  before_action :require_same_user, only: %i[ edit update destory ]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can edit or delete only YOUR OWN article"
        redirect_to @article
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: %i[ index show ]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfuly"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admin can perform that action"
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        redirect_to articles_path if (current_user && current_user.admin?)
    end

    def about
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_user, only: %i[ edit update ]
  before_action :require_same_user, only: %i[ edit update destroy ]

  def show 
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Account succesfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all articles successfully deleted"
    redirect_to root_path
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the BLOG #{@user.username} we are glad to see you!"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user !=  @user && !current_user.admin?
      flash[:alert] = "You can edit only YOUR OWN account"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-thumbnail shadow rounded mx-auto d-block")
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% @articles.each do |article| %>
  <div class="card text-center card shadow mb-5 bg-color rounded">
    <div class="card-header bg-new">
      <ul class="nav nav-pills card-header-pills d-grid gap-2 d-md-flex justify-content-md-end">
        <li class="nav-item">
          <%= link_to 'Show', article_path(article), class: "btn btn-outline-primary btn-sm" %>
        </li>
        <% if logged_in? && (article.user == current_user || current_user.admin?) %>
          <li class="nav-item">
            <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-success btn-sm" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Delete', article_path(article), class: "btn btn-outline-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>
          </li>
        <% end %>
      </ul>
      <% if article.categories.any? %>
        <div class = "mt-2"><%= render article.categories %></div>
      <% end %>
    </div>
    <div class="card-body">
      <h5 class="card-title fs-2" ><%= link_to article.title, article_path(article), class: "text-decoration-none text-dark" %></h5>
      <p class="card-text fs-5"><%= truncate(article.description, length: 100) %></p>
    </div>
    <div class="card-footer text-muted fs-6 bg-new">
      Created <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at) %> ago 
      <span class="fst-italic">
        <% if article.user %>
          by <%= link_to article.user.username, user_path(article.user), class:  "text-decoration-none text-dark" %>
        <% end %>
      </span>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<div class="container shadow  p-3 rounded-3">
  <%= render 'shared/errors', obj: @article %> 
  <%= form_with(model: @article) do |form| %>
    <form>
      <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
        <div id="help" class="form-text">Length must be more than 6 characters and less than 100</div>
      </div>
      <div class="mb-3">
        <%= form.label :description, class: "form-label" %>
        <%= form.text_area :description, class: "form-control", rows: "4" %>
        <div id="help" class="form-text">Length must be more than 10 characters and less than 500</div>
      </div>
      <div class="mb-3">
        <%= form.label :category, class: "form-label" %>
        <%= form.collection_select :category_ids, Category.all, :id, :name, 
        { prompt: "(empty)"}, { multiple: true, size: 3, class: "form-control w-50 overflow-auto"} %>
        <div id="help" class="form-text">To select more than one press control</div>
      </div>
      <div class="actions">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    </form> 
  <% end %>
  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4 text-white fw-bold" >Edit your article</h1>
<%= render 'form'%>

app/views/articles/index.html.erb
<h1 class="text-center mt-4 text-white fw-bold" >Listing all articles</h1>

<div class="apple_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="apple_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4 text-white fw-bold" >Add new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4 text-white fw-bold" ><%= @article.title %></h1>

<div class="card text-center card shadow mb-5 bg-color rounded">
  <div class="card-header bg-new">
    <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
    <% if @article.categories.any? %>
      <div class = "mt-2"><%= render @article.categories %></div>
    <% end %>
    <ul class="nav nav-pills card-header-pills d-grid gap-2 d-md-flex justify-content-md-end">
      <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
        <li class="nav-item">
          <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-success btn-sm" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Delete', article_path(@article), class: "btn btn-outline-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="card-body">
    <div class="card-text fs-5 text-start"><%= @article.description %></div>
  </div>
  <div class="card-footer text-muted bg-new">
    Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago 
    <span class="fst-italic">
      by <%= @article.user.username if @article.user %>
    </span>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), 
class: "badge rounded-pill bg-secondary me-1 text-decoration-none border border-light" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %> 
<%= form_with(model: @category) do |form| %>
  <form>
    <div class="mb-3">
      <%= form.label :name, "Category name", class: "form-label" %>
      <%= form.text_field :name, class: "form-control"%>
      <div id="help" class="form-text">Enter a name</div>
    </div>
    <div class="actions">
      <%= form.submit class: "btn btn-primary"%>
    </div>
  </form> 
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4 text-white fw-bold" >Edit category name</h1>
 
<div class="container shadow w-50 p-3 rounded-3">
  <%= render 'form'%>
  <%= link_to 'Back', category_path(@category) %>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4 text-white fw-bold" >Categories</h1>

<div class="apple_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<% @categories.each do |category| %>
  <div class="card text-center card shadow mb-5 bg-color rounded">
    <div class="card-body">
      <h5 class="card-title fs-2" ><%= link_to category.name, category_path(category), class: "text-decoration-none text-dark" %></h5>
      <p class="card-text fs-5"><%= pluralize(category.articles.count, "article") %></p>
      </div>
    <div class="card-footer text-muted fs-6 bg-new">
      Created <%= time_ago_in_words(category.created_at) %> ago, edited <%= time_ago_in_words(category.updated_at) %> ago 
    </div>
  </div>
<% end %>

<div class="apple_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4 text-white fw-bold" >Create a new category</h1>
 
<div class="container shadow w-50 p-3 rounded-3">
  <%= render 'form'%>
  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4 text-white fw-bold">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-primary btn-sm" %>
  </div>
<% end %>

<h2 class="text-center mt-4 text-white fw-bold" >Articles</h2>

<div class="apple_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="apple_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <a>Copyright &copy; TheJudgeMonkey</a>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light nav-color">
  <div class="container-fluid">
    <%= link_to "BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "BLOGGERS", users_path, class: "nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu bg-color" aria-labelledby="navbarDropdown">
            <li><%= link_to "All articles", articles_path, class: "dropdown-item fw" %></li>
            <li><%= link_to "All categories", categories_path, class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if current_user && current_user.admin? %>  
              <span class="badge bg-secondary">ADMIN</span> account
            <% else %>
              Account
            <% end %>
          </a>
          <ul class="dropdown-menu bg-color" aria-labelledby="navbarDropdown">
            <% if logged_in? %>
              <li><%= link_to " Welcome #{current_user.username}!", user_path(current_user), class: "dropdown-item fw-bold" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Create New Category", new_category_path, class: "dropdown-item text-success" if current_user.admin? %></li>
              <li><%= link_to "Create New Article", new_article_path, class: "dropdown-item text-success"%></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Logout", logout_path, class: "dropdown-item  text-danger", method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign up", signup_path, class: "dropdown-item text-primary" %></li>
              <li><%= link_to "Log in", login_path, class: "dropdown-item text-success" %></li>
            <% end %>        
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link"%>
        </li>    
      </ul>  
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="text-center mt-4 text-white fw-bold" >About page</h1>

<div class="card text-center card shadow mb-5 bg-color rounded">
  <div class="card-header bg-new fs-4">
    This is a project by 
    <%= link_to "Stas Anufriev", "https://github.com/TheJudgeMonkey/project_blog", class: "text-decoration-none text-light" %> 
    for
    <%= link_to "iTechArt", " https://www.itechart.by", class: "text-decoration-none text-light" %>
  </div>
  <div class="card-body">
    <div class="card-text text-start">
      <h6 class="text-center fs-5">This is a project "BLOG" for iTechArt by course Udemy(Mashrur Hossain)</h6>
      <ul class="fs-5">
        <li>One-to-many associations</li>
        <li>Many-to-many associations</li>
        <li>BCrypt(v.3.1.7) secure password</li>
        <li>Bootstrap(v.5.0) styling</li>
        <li>Tests for categories</li>
        <li>Ruby v.2.7.2</li>
        <li>Rails v.6.1.4</li>
      </ul>
    </div>
  </div>
  <div class="card-footer text-muted bg-new">
    <ul class="nav nav-pills card-header-pills d-grid gap-2 d-md-flex justify-content-md-center">
      <li class="nav-item">
        <%= link_to 'Articles', articles_path, class: "btn btn-outline-success btn-sm" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Home page', root_path, class: "btn btn-outline-primary btn-sm" %>
      </li>
    </ul>
  </div>
</div>

app/views/pages/home.html.erb
<div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("book.jpg", class: "d-block w-100") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("books.jpg", class: "d-block w-100") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("sea.jpg", class: "d-block w-100") %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading"><%= pluralize(obj.errors.count, "error") %> prohibited this <%= obj.class.name.downcase %> from being saved:</h4>
    <ul>
      <% obj.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true"></button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container shadow w-50 p-3 rounded-3">
  <%= render 'shared/errors', obj: @user %> 
  <%= form_with(model: @user) do |form| %>
    <form>
      <div class="mb-3">
        <%= form.label :username, class: "form-label" %>
        <%= form.text_field :username, class: "form-control"%>
        <div id="help" class="form-text">Enter a username</div>
      </div>
      <div class="mb-3">
        <%= form.label :email, class: "form-label" %>
        <%= form.email_field :email, class: "form-control"%>
        <div id="help" class="form-text">Enter your email</div>
      </div>
      <div class="mb-3">
        <%= form.label :password, class: "form-label" %>
        <%= form.password_field :password, class: "form-control"%>
        <div id="help" class="form-text">Enter your password</div>
      </div>
      <div class="actions">
        <%= form.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary")%>
      </div>
    </form> 
  <% end %>
  <%= link_to 'Back', articles_path %>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4 text-white fw-bold" >Edit your profile</h1>
<%= render 'form'%>

app/views/users/index.html.erb
<h1 class="text-center mt-4 text-white fw-bold" >BLOGGERS</h1>

<div class="apple_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<% @users.each do |user| %>
  <div class="card text-center card shadow mb-5 bg-color rounded">
    <div class="card-header bg-new">
      <%= link_to user.username, user, class: "text-decoration-none text-dark fs-2" %>
    </div>
    <div class="card-body">
      <h5 class="card-title fs-2" >
        <%= link_to gravatar_for(user, size: 150), user %>
      </h5>
      <p class="card-text fs-5"><%= pluralize(user.articles.count, "article") %></p>
    </div>
    <div class="card-footer text-muted fs-6 bg-new">
      <ul class="nav nav-pills card-header-pills d-grid gap-2 d-md-flex justify-content-md-end">
        <li class="nav-item">
          <%= link_to 'View profile', user, class: "btn btn-outline-success btn-sm" %>
        </li>
        <% if logged_in?  %>
          <% if user == current_user %>
            <li class="nav-item">
              <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-primary btn-sm" %>
            </li>
          <% end %>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to 'Delete user', user_path(user), class: "btn btn-outline-danger btn-sm",
              method: :delete, data: {confirm: "Are you sure you want to delete user account?"} %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="apple_pagination mb-4">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4 text-white fw-bold" >Sign up for BLOG</h1>
<%= render 'form'%>

app/views/users/show.html.erb
<h1 class="text-center mt-4 text-white fw-bold" ><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-primary btn-sm" %>
    <%= link_to "Delete profile", user_path(@user), class: "btn btn-outline-danger btn-sm", method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
<% end %>

<h2 class="text-center mt-4 text-white fw-bold" >Articles</h2>

<div class="apple_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="apple_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>